pipeline {
    agent any
stages {
        stage('Run Python Script') {
            steps {
                script {
                    if (resource == 'ec2'){
                        def command = "python3 platform_engineering/main.py --resource ec2 --action ${action}"

                        if (action == 'create') {
                            command += " --type ${type} --image ${image}"
                        } else if (action == 'manage') {
                            command = "python3  platform_engineering/main.py --resource ec2 --action manage --status ${type} --instance ${spesiific_ids}"
                            } 
                        
                        sh command
                        
                    } else if (resource == 's3'){
                        def command = "python3 platform_engineering/main.py --resource s3 --action ${action}"

                        if (action == 'create'){
                            command += " --choice ${security}"
                        } else if (action == 'manage') {
                            command = "python3 platform_engineering/main.py --resource s3 --action manage --file ${file_path} --name ${file_name}"
                        }
                        
                        sh command
                    }
                    
                    }
                }
            }
        }


    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}